export { default as DiscordIcon } from './DiscordIcon'
export { default as GithubIcon } from './GithubIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as LinkedInIcon } from './LinkedInIcon'
export { default as Logo } from './Logo'
export { default as MenuIcon } from './MenuIcon'
export { default as NextjsIcon } from './NextjsIcon'
export { default as TwitterIcon } from './TwitterIcon'
