export { default as Layout } from './Layout'
export { default as Footer } from './Footer'
export { default as Head } from './Head'
export { default as Header } from './Header'
export { default as Icon } from './Icon'
export { default as I18nWidget } from './I18nWidget'
export { default as Title } from './Text/Title'
