export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as ContactPreview } from './ContactPreview'
export { default as Hero } from './Hero'
export { default as Loader } from './Loader'
export { default as Projects } from './Projects'
export { default as ProjectsPreview } from './ProjectsPreview'
export { default as Sidebar } from './Sidebar'
